import type { Project, ProjectConfig, StatusConfig, Task, TaskTemplate } from '../types'
import { isTerminalStatus, sanitizeFileName } from '../utils'
import { appendYaml, FRONTMATTER_KEY, stripAutoGeneratedContent, TASK_FRONTMATTER_KEY, TEMPLATE_FRONTMATTER_KEY } from './YamlParser'

// ─── Serialize ──────────────────────────────────────────────────────────────

/** Only the fields a project actually overrides are written; an empty override block is omitted. */
function serializeProjectConfig(config: ProjectConfig | undefined): Record<string, unknown> | null {
  if (!config) return null
  const out: Record<string, unknown> = {}
  if (config.statuses?.length) out.statuses = config.statuses
  if (config.priorities?.length) out.priorities = config.priorities
  if (config.defaultView) out.defaultView = config.defaultView
  if (config.autoSchedule !== undefined) out.autoSchedule = config.autoSchedule
  if (config.kanbanShowSubtasks !== undefined) out.kanbanShowSubtasks = config.kanbanShowSubtasks
  if (config.kanbanShowDescriptionPreview !== undefined) {
    out.kanbanShowDescriptionPreview = config.kanbanShowDescriptionPreview
  }
  return Object.keys(out).length ? out : null
}

export function serializeProject(project: Project, statuses: StatusConfig[] = []): string {
  const seen = new Set<string>()
  const tasks: Task[] = []
  for (const t of project.tasks) {
    if (seen.has(t.id)) continue
    seen.add(t.id)
    tasks.push(t)
  }
  const taskIds = tasks.map((t) => t.id)

  const fm: Record<string, unknown> = {
    [FRONTMATTER_KEY]: true,
    id: project.id,
    title: project.title,
    description: project.description,
    color: project.color,
    icon: project.icon,
    taskIds,
    customFields: project.customFields,
    savedViews: project.savedViews.length ? project.savedViews : [],
    createdAt: project.createdAt,
    updatedAt: project.updatedAt
  }
  const config = serializeProjectConfig(project.config)
  if (config) fm.config = config

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  yamlLines.push('---')
  yamlLines.push('')
  yamlLines.push(`# ${project.icon} ${project.title}`)
  yamlLines.push('')
  if (project.description) {
    yamlLines.push(project.description)
    yamlLines.push('')
  }
  if (tasks.length) {
    yamlLines.push('## Tasks')
    for (const t of tasks) {
      if (t.filePath) {
        const basename = t.filePath.replace(/^.*\//, '').replace(/\.md$/, '')
        const check = isTerminalStatus(t.status, statuses) ? 'x' : ' '
        yamlLines.push(`- [${check}] [[${basename}|${t.title}]]`)
      }
    }
    yamlLines.push('')
  }

  return yamlLines.join('\n')
}

export function buildTaskFrontmatter(task: Task, project: Project, parentTask: Task | null): Record<string, unknown> {
  const fm: Record<string, unknown> = {
    [TASK_FRONTMATTER_KEY]: true,
    projectId: project.id,
    parentId: parentTask?.id ?? null,
    id: task.id,
    title: task.title,
    type: task.type,
    status: task.status,
    priority: task.priority,
    start: task.start,
    due: task.due,
    progress: task.progress,
    tags: task.tags,
    subtaskIds: task.subtasks.map((s) => s.id),
    dependencies: task.dependencies,
    createdAt: task.createdAt,
    updatedAt: task.updatedAt
  }
  if (task.completed) fm.completed = task.completed
  if (task.recurrence) fm.recurrence = task.recurrence
  if (task.templateId) fm.templateId = task.templateId
  if (task.timeEstimate !== undefined) fm.timeEstimate = task.timeEstimate
  if (task.timeLogs?.length) fm.timeLogs = task.timeLogs
  if (Object.keys(task.customFields).length) fm.customFields = task.customFields
  return fm
}

export function serializeTask(
  task: Task,
  project: Project,
  parentTask: Task | null,
  statuses: StatusConfig[] = []
): string {
  const fm = buildTaskFrontmatter(task, project, parentTask)

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  yamlLines.push('---')
  yamlLines.push('')
  const cleanDesc = stripAutoGeneratedContent(task.description)
  if (cleanDesc) {
    yamlLines.push(cleanDesc)
    yamlLines.push('')
  }

  if (parentTask?.filePath) {
    const parentBasename = parentTask.filePath.replace(/^.*\//, '').replace(/\.md$/, '')
    yamlLines.push(`Parent: [[${parentBasename}|${parentTask.title}]]`)
  } else {
    const projectBasename = project.filePath.replace(/^.*\//, '').replace(/\.md$/, '')
    yamlLines.push(`Project: [[${projectBasename}|${project.title}]]`)
  }

  if (task.subtasks.length) {
    yamlLines.push('')
    yamlLines.push('## Subtasks')
    for (const sub of task.subtasks) {
      const subBasename = sub.filePath ? sub.filePath.replace(/^.*\//, '').replace(/\.md$/, '') : slugify(sub.title)
      const check = isTerminalStatus(sub.status, statuses) ? 'x' : ' '
      yamlLines.push(`- [${check}] [[${subBasename}|${sub.title}]]`)
    }
  }

  return yamlLines.join('\n')
}

/** Slug length cap, for path-length safety (Windows MAX_PATH, mobile, sync). */
export const TASK_SLUG_MAX_LENGTH = 60

export function slugify(title: string): string {
  return sanitizeFileName(title).toLowerCase().replace(/\s+/g, '-').slice(0, TASK_SLUG_MAX_LENGTH)
}

/** Build the file path for a task .md file */
export function taskFilePath(taskTitle: string, folder: string): string {
  return `${folder}/${slugify(taskTitle)}.md`
}

/** Build frontmatter for a template .md file */
export function buildTemplateFrontmatter(template: TaskTemplate): Record<string, unknown> {
  return {
    [TEMPLATE_FRONTMATTER_KEY]: true,
    id: template.id,
    name: template.name,
    subtasks: template.subtasks.map((s) => ({ title: s.title }))
  }
}

/** Serialize a template to .md string */
export function serializeTemplate(template: TaskTemplate): string {
  const fm = buildTemplateFrontmatter(template)
  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  yamlLines.push('---')
  yamlLines.push('')
  yamlLines.push(`# ${template.name}`)
  yamlLines.push('')
  return yamlLines.join('\n')
}

/** Build the file path for a template .md file */
export function templateFilePath(templateName: string, folder: string): string {
  return `${folder}/${slugify(templateName)}.md`
}
