import type {
  CustomFieldDef,
  PriorityConfig,
  Project,
  ProjectConfig,
  SavedView,
  StatusConfig,
  Task,
  TaskTemplate,
  ViewMode
} from '../types'
import { makeTask, makeTemplate } from '../types'
import { stripAutoGeneratedContent, TEMPLATE_FRONTMATTER_KEY } from './YamlParser'

// ─── Hydrate ────────────────────────────────────────────────────────────────

export function hydrateSavedViews(raw: unknown[]): SavedView[] {
  if (!Array.isArray(raw)) return []
  return raw
    .filter((r) => r && typeof r === 'object')
    .map((r) => {
      const v = r as Record<string, unknown>
      const filter = (v.filter ?? {}) as Record<string, unknown>
      const viewMode = v.viewMode
      const validViewMode: ViewMode | undefined =
        viewMode === 'table' || viewMode === 'gantt' || viewMode === 'kanban' ? viewMode : undefined
      return {
        id: (v.id as string) ?? '',
        name: (v.name as string) ?? 'Untitled',
        filter: {
          text: (filter.text as string) ?? '',
          statuses: Array.isArray(filter.statuses) ? filter.statuses : [],
          priorities: Array.isArray(filter.priorities) ? filter.priorities : [],
          tags: Array.isArray(filter.tags) ? filter.tags : [],
          dueDateFilter: (filter.dueDateFilter as string as SavedView['filter']['dueDateFilter']) ?? 'any',
          showArchived: (filter.showArchived as boolean) ?? false
        },
        sortKey: (v.sortKey as string) ?? 'status',
        sortDir: (v.sortDir as 'asc' | 'desc') ?? 'asc',
        ...(validViewMode ? { viewMode: validViewMode } : {})
      }
    })
}

/** Map raw frontmatter fields to a Task, with optional overrides */
export function mapRawToTask(r: Record<string, unknown>, overrides?: Partial<Task>): Task {
  return makeTask({
    id: r.id as string,
    title: (r.title as string) ?? 'Untitled',
    description: (r.description as string) ?? '',
    type: (r.type as string) === 'milestone' ? 'milestone' : (r.type as string) === 'subtask' ? 'subtask' : 'task',
    status: (r.status as Task['status']) ?? 'todo',
    priority: (r.priority as Task['priority']) ?? 'medium',
    start: (r.start as string) ?? '',
    due: (r.due as string) ?? '',
    progress: typeof r.progress === 'number' ? r.progress : 0,
    completed: (r.completed as string) ?? '',
    // Copy container fields rather than aliasing them. On the metadataCache
    // fast path `r` is Obsidian's live frontmatter object, so a shared array or
    // object would let an in-place task mutation corrupt the cache.
    tags: Array.isArray(r.tags) ? [...(r.tags as string[])] : [],
    subtasks: [],
    dependencies: Array.isArray(r.dependencies) ? [...(r.dependencies as string[])] : [],
    recurrence:
      r.recurrence && typeof r.recurrence === 'object'
        ? ({ ...(r.recurrence as Task['recurrence']) } as Task['recurrence'])
        : undefined,
    timeEstimate: typeof r.timeEstimate === 'number' ? r.timeEstimate : undefined,
    timeLogs: Array.isArray(r.timeLogs)
      ? (r.timeLogs as { date: string; hours: number; note: string }[]).map((log) => ({ ...log }))
      : undefined,
    customFields:
      typeof r.customFields === 'object' && r.customFields !== null
        ? { ...(r.customFields as Record<string, unknown>) }
        : {},
    collapsed: r.collapsed === true,
    createdAt: (r.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (r.updatedAt as string) ?? new Date().toISOString(),
    ...overrides
  })
}

export function hydrateTasks(raw: unknown[]): Task[] {
  if (!Array.isArray(raw)) return []
  return raw.map((r) => {
    const rec = r as Record<string, unknown>
    return mapRawToTask(rec, {
      subtasks: Array.isArray(rec.subtasks) ? hydrateTasks(rec.subtasks as unknown[]) : []
    })
  })
}

/** Hydrate a task from its frontmatter + body (individual .md file) */
export function hydrateTaskFromFile(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string
): { task: Task; subtaskIds: string[]; parentId: string | null } {
  const task = mapRawToTask(frontmatter, {
    description: stripAutoGeneratedContent(body),
    filePath
  })
  const subtaskIds = Array.isArray(frontmatter.subtaskIds) ? (frontmatter.subtaskIds as string[]) : []
  const parentId = typeof frontmatter.parentId === 'string' && frontmatter.parentId ? frontmatter.parentId : null
  return { task, subtaskIds, parentId }
}

/** Hydrate a TaskTemplate from a template file's frontmatter */
export function hydrateTemplateFromFile(frontmatter: Record<string, unknown>, filePath: string): TaskTemplate | null {
  if (frontmatter[TEMPLATE_FRONTMATTER_KEY] !== true) return null
  const template = makeTemplate((frontmatter.name as string) ?? 'Untitled')
  template.id = (frontmatter.id as string) ?? template.id
  if (Array.isArray(frontmatter.subtasks)) {
    template.subtasks = (frontmatter.subtasks as { title: string }[]).map((s) => ({ title: s.title ?? '' }))
  }
  return template
}

/** Build a Project object from frontmatter + body (without tasks) */
export function hydrateProjectFromFrontmatter(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
  basename: string
): Project {
  return {
    id: (frontmatter.id as string) ?? basename,
    title: (frontmatter.title as string) ?? basename,
    description: (frontmatter.description as string) ?? body.trim(),
    color: (frontmatter.color as string) ?? '#8b72be',
    icon: (frontmatter.icon as string) ?? '\u{1F4CB}',
    tasks: [],
    // Copy containers: on the metadataCache fast path `frontmatter` is Obsidian's
    // live object, so sharing these arrays would let an in-place edit corrupt the cache.
    customFields: Array.isArray(frontmatter.customFields) ? [...(frontmatter.customFields as CustomFieldDef[])] : [],
    taskTemplates: [],
    createdAt: (frontmatter.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (frontmatter.updatedAt as string) ?? new Date().toISOString(),
    filePath,
    savedViews: hydrateSavedViews((frontmatter.savedViews as unknown[]) ?? []),
    config: hydrateProjectConfig(frontmatter.config),
    taskIndex: new Map()
  }
}

/** Read a project's settings overrides, dropping malformed fields. Absent or empty = inherit everything. */
function hydrateProjectConfig(raw: unknown): ProjectConfig | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const r = raw as Record<string, unknown>
  const config: ProjectConfig = {}
  const statuses = hydrateStatusList(r.statuses)
  if (statuses) config.statuses = statuses
  const priorities = hydratePriorityList(r.priorities)
  if (priorities) config.priorities = priorities
  if (r.defaultView === 'table' || r.defaultView === 'gantt' || r.defaultView === 'kanban') {
    config.defaultView = r.defaultView
  }
  if (typeof r.autoSchedule === 'boolean') config.autoSchedule = r.autoSchedule
  if (typeof r.kanbanShowSubtasks === 'boolean') config.kanbanShowSubtasks = r.kanbanShowSubtasks
  if (typeof r.kanbanShowDescriptionPreview === 'boolean') {
    config.kanbanShowDescriptionPreview = r.kanbanShowDescriptionPreview
  }
  return Object.keys(config).length ? config : undefined
}

function hydrateStatusList(raw: unknown): StatusConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const statuses: StatusConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const s = entry as Partial<StatusConfig>
    if (typeof s.id !== 'string' || !s.id) continue
    statuses.push({
      id: s.id,
      label: typeof s.label === 'string' ? s.label : s.id,
      color: typeof s.color === 'string' ? s.color : '#8a94a0',
      icon: typeof s.icon === 'string' ? s.icon : '',
      complete: s.complete === true
    })
  }
  return statuses.length ? statuses : undefined
}

function hydratePriorityList(raw: unknown): PriorityConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const priorities: PriorityConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const p = entry as Partial<PriorityConfig>
    if (typeof p.id !== 'string' || !p.id) continue
    priorities.push({
      id: p.id,
      label: typeof p.label === 'string' ? p.label : p.id,
      color: typeof p.color === 'string' ? p.color : '#8a94a0',
      icon: typeof p.icon === 'string' ? p.icon : ''
    })
  }
  return priorities.length ? priorities : undefined
}
